#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : libqalculate
Version  : 5.2.0
Release  : 14
URL      : https://github.com/Qalculate/libqalculate/releases/download/v5.2.0/libqalculate-5.2.0.tar.gz
Source0  : https://github.com/Qalculate/libqalculate/releases/download/v5.2.0/libqalculate-5.2.0.tar.gz
Summary  : libqalculate
Group    : Development/Tools
License  : GPL-2.0
Requires: libqalculate-bin = %{version}-%{release}
Requires: libqalculate-data = %{version}-%{release}
Requires: libqalculate-lib = %{version}-%{release}
Requires: libqalculate-license = %{version}-%{release}
Requires: libqalculate-locales = %{version}-%{release}
Requires: libqalculate-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : doxygen
BuildRequires : gettext
BuildRequires : gmp-dev
BuildRequires : intltool
BuildRequires : mpfr-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(icu-uc)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : readline-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Qalculate! library and CLI
Qalculate! is a multi-purpose cross-platform desktop calculator. It is simple
to use but provides power and versatility normally reserved for complicated
math packages, as well as useful tools for everyday needs (such as currency
conversion and percent calculation). Features include a large library of
customizable functions, unit calculations and conversion, symbolic calculations
(including integrals and equations), arbitrary precision, uncertainty
propagation, interval arithmetic, plotting, and a user-friendly interface (GTK+,
Qt, and CLI).

%package bin
Summary: bin components for the libqalculate package.
Group: Binaries
Requires: libqalculate-data = %{version}-%{release}
Requires: libqalculate-license = %{version}-%{release}

%description bin
bin components for the libqalculate package.


%package data
Summary: data components for the libqalculate package.
Group: Data

%description data
data components for the libqalculate package.


%package dev
Summary: dev components for the libqalculate package.
Group: Development
Requires: libqalculate-lib = %{version}-%{release}
Requires: libqalculate-bin = %{version}-%{release}
Requires: libqalculate-data = %{version}-%{release}
Provides: libqalculate-devel = %{version}-%{release}
Requires: libqalculate = %{version}-%{release}

%description dev
dev components for the libqalculate package.


%package doc
Summary: doc components for the libqalculate package.
Group: Documentation
Requires: libqalculate-man = %{version}-%{release}

%description doc
doc components for the libqalculate package.


%package lib
Summary: lib components for the libqalculate package.
Group: Libraries
Requires: libqalculate-data = %{version}-%{release}
Requires: libqalculate-license = %{version}-%{release}

%description lib
lib components for the libqalculate package.


%package license
Summary: license components for the libqalculate package.
Group: Default

%description license
license components for the libqalculate package.


%package locales
Summary: locales components for the libqalculate package.
Group: Default

%description locales
locales components for the libqalculate package.


%package man
Summary: man components for the libqalculate package.
Group: Default

%description man
man components for the libqalculate package.


%prep
%setup -q -n libqalculate-5.2.0
cd %{_builddir}/libqalculate-5.2.0
pushd ..
cp -a libqalculate-5.2.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719967990
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || : || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719967990
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libqalculate
cp %{_builddir}/libqalculate-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libqalculate/4cc77b90af91e615a64ae04893fdffa7939db84c || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
%find_lang libqalculate
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/qalc
/usr/bin/qalc

%files data
%defattr(-,root,root,-)
/usr/share/qalculate/currencies.xml
/usr/share/qalculate/datasets.xml
/usr/share/qalculate/elements.xml
/usr/share/qalculate/eurofxref-daily.xml
/usr/share/qalculate/functions.xml
/usr/share/qalculate/planets.xml
/usr/share/qalculate/prefixes.xml
/usr/share/qalculate/rates.json
/usr/share/qalculate/units.xml
/usr/share/qalculate/variables.xml

%files dev
%defattr(-,root,root,-)
/usr/include/libqalculate/BuiltinFunctions.h
/usr/include/libqalculate/Calculator.h
/usr/include/libqalculate/DataSet.h
/usr/include/libqalculate/ExpressionItem.h
/usr/include/libqalculate/Function.h
/usr/include/libqalculate/MathStructure.h
/usr/include/libqalculate/Number.h
/usr/include/libqalculate/Prefix.h
/usr/include/libqalculate/QalculateDateTime.h
/usr/include/libqalculate/Unit.h
/usr/include/libqalculate/Variable.h
/usr/include/libqalculate/includes.h
/usr/include/libqalculate/qalculate.h
/usr/include/libqalculate/util.h
/usr/lib64/libqalculate.so
/usr/lib64/pkgconfig/libqalculate.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libqalculate/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libqalculate.so.23.2.0
/usr/lib64/libqalculate.so.23
/usr/lib64/libqalculate.so.23.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libqalculate/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/qalc.1

%files locales -f libqalculate.lang
%defattr(-,root,root,-)

