#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libqalculate
Version  : 2.6.2
Release  : 1
URL      : https://github.com/Qalculate/libqalculate/releases/download/v2.6.2/libqalculate-2.6.2.tar.gz
Source0  : https://github.com/Qalculate/libqalculate/releases/download/v2.6.2/libqalculate-2.6.2.tar.gz
Summary  : libqalculate
Group    : Development/Tools
License  : GPL-2.0
Requires: libqalculate-bin
Requires: libqalculate-lib
Requires: libqalculate-license
Requires: libqalculate-locales
Requires: libqalculate-data
BuildRequires : gettext
BuildRequires : gmp-dev
BuildRequires : intltool
BuildRequires : mpfr-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(icu-uc)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : readline-dev

%description
Qalculate! library and CLI
Qalculate! is a multi-purpose cross-platform desktop calculator.
It is simple to use but provides power and versatility normally reserved for complicated math packages,
as well as useful tools for everyday needs (such as currency conversion and percent calculation).
Features include a large library of customizable functions, unit calculations and conversion,
symbolic calculations (including integrals and equations), arbitrary precision, interval arithmetic,
plotting, and a user-friendly interface (GTK+ and CLI).

%package bin
Summary: bin components for the libqalculate package.
Group: Binaries
Requires: libqalculate-data
Requires: libqalculate-license

%description bin
bin components for the libqalculate package.


%package data
Summary: data components for the libqalculate package.
Group: Data

%description data
data components for the libqalculate package.


%package dev
Summary: dev components for the libqalculate package.
Group: Development
Requires: libqalculate-lib
Requires: libqalculate-bin
Requires: libqalculate-data
Provides: libqalculate-devel

%description dev
dev components for the libqalculate package.


%package doc
Summary: doc components for the libqalculate package.
Group: Documentation

%description doc
doc components for the libqalculate package.


%package lib
Summary: lib components for the libqalculate package.
Group: Libraries
Requires: libqalculate-data
Requires: libqalculate-license

%description lib
lib components for the libqalculate package.


%package license
Summary: license components for the libqalculate package.
Group: Default

%description license
license components for the libqalculate package.


%package locales
Summary: locales components for the libqalculate package.
Group: Default

%description locales
locales components for the libqalculate package.


%prep
%setup -q -n libqalculate-2.6.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535491575
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1535491575
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libqalculate
cp COPYING %{buildroot}/usr/share/doc/libqalculate/COPYING
%make_install
%find_lang libqalculate

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qalc

%files data
%defattr(-,root,root,-)
/usr/share/qalculate/currencies.xml
/usr/share/qalculate/datasets.xml
/usr/share/qalculate/elements.xml
/usr/share/qalculate/eurofxref-daily.xml
/usr/share/qalculate/functions.xml
/usr/share/qalculate/planets.xml
/usr/share/qalculate/prefixes.xml
/usr/share/qalculate/rates.json
/usr/share/qalculate/units.xml
/usr/share/qalculate/variables.xml

%files dev
%defattr(-,root,root,-)
/usr/include/libqalculate/BuiltinFunctions.h
/usr/include/libqalculate/Calculator.h
/usr/include/libqalculate/DataSet.h
/usr/include/libqalculate/ExpressionItem.h
/usr/include/libqalculate/Function.h
/usr/include/libqalculate/MathStructure.h
/usr/include/libqalculate/Number.h
/usr/include/libqalculate/Prefix.h
/usr/include/libqalculate/QalculateDateTime.h
/usr/include/libqalculate/Unit.h
/usr/include/libqalculate/Variable.h
/usr/include/libqalculate/includes.h
/usr/include/libqalculate/qalculate.h
/usr/include/libqalculate/util.h
/usr/lib64/libqalculate.so
/usr/lib64/pkgconfig/libqalculate.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libqalculate/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libqalculate.so.19
/usr/lib64/libqalculate.so.19.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/libqalculate/COPYING

%files locales -f libqalculate.lang
%defattr(-,root,root,-)

